### ISSUE TITLE
[Suggestion] Use gxman for installing 3gxtool

### ISSUE THREAD

**Issue by HIDE810** [ponpoko094/Colorful-MHX3gx#34]
gxman is my personal project to simplify installing 3gxtool.
If Golang(>=1.16) is installed on your system, you can install it by the following command.

```
go install github.com/HIDE810/gxman@latest
```

If you want to install the latest 3gxtool which has no 1 MiB limit, use the following command.

```
gxman get -u
```

If you like this, I would apreciate it if you add this description in `README.md`.

**Comment by ponpoko094** [comment]
Added a description of gxman to `README.md`.

**Comment by HIDE810** [comment]
Thank you!
